name: ezamizone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    dio: ^5.5.0+1
    flip_card: ^0.7.0
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.4.1
    get: ^4.6.6
    get_storage: ^2.1.1
    google_mobile_ads: ^5.1.0
    provider: ^6.1.2
    url_launcher: ^6.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
